service: hello-api

provider:
  name: aws
  region: us-east-1
  runtime: nodejs8.10
  profile: bmt-home
  environment: ${file(env.yml):${opt:stage, self:provider.stage}}

#  iamRoleStatements:
#      - Effect: Allow
#        Action:
#          - dynamodb:DescribeTable
#          - dynamodb:Query
#          - dynamodb:Scan
#          - dynamodb:GetItem
#          - dynamodb:PutItem
#          - dynamodb:DeleteItem
#          - dynamodb:UpdateItem
#          - dynamodb:BatchGetItem
#          - dynamodb:BatchWriteItem
#        Resource: arn:aws:dynamodb:*:*:${self:provider.environment.TABLE}
#      - Effect: Allow
#        Action:
#          - s3:*
#        Resource: arn:aws:s3:*:*:${self:provider.environment.BUCKET}

custom:
  dirconfig:
      quiet: true
  webpack:
      webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
      includeModules: false
#        forceExclude:
#          - aws-sdk
      packager: 'npm'   # Packager that will be used to package your external modules

plugins:
  - serverless-webpack
  - serverless-dir-config-plugin
