service: hello-api

provider:
  name: aws
  region: us-east-1
  runtime: nodejs8.10
  profile: bmt-home
  environment: ${file(env.yml):${opt:stage, self:provider.stage}}

  iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:DescribeTable
          - dynamodb:Query
          - dynamodb:Scan
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:DeleteItem
          - dynamodb:UpdateItem
          - dynamodb:BatchGetItem
          - dynamodb:BatchWriteItem
          - s3:*
        Resource: "*"

custom:
  dirconfig:
      quiet: true
  webpack:
      webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
      includeModules: false
#        forceExclude:
#          - aws-sdk
      packager: 'npm'   # Packager that will be used to package your external modules
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true

plugins:
  - serverless-webpack
  - serverless-dir-config-plugin
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-plugin-existing-s3
